log_dir: "logs/aihub_muilti_lingual_jp"
save_freq: 5
device: "cuda"
epochs: 200
batch_size: 32

pretrained_model: ""
load_only_params: False
train_data: "Data/train_multi_lingual_jp_filelist.txt.cleaned.cutted.valid_word"
val_data: "Data/valid_multi_lingual_jp_600_filelist.txt.cleaned.valid_word"

dataset_params:
  root_path: "../../datasets/AIHUB/"

preprocess_parasm:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300
  mel_params:
    n_mels: 80

model_params:
   input_dim: 80
   hidden_dim: 256
   n_token: 270
   token_embedding_dim: 512

optimizer_params:
  lr: 0.0005